server:
  port: 9001
spring:
  application:
    name: APIGateway
  cloud:
   gateway:
    routes:
     - id: GeneratePensionerDetails
       uri: lb://GeneratePensionerDetails
       predicates:
        - Path=/PensionerDetailByAadhaar/**
     - id: ProcesPension
       uri: lb://ProcesPension
       predicates:
        - Path=/ProcessPension/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
    fetch-registry: true
    register-with-eureka: true