server:
  port: 9005
spring:
  application:
    name: APIGateway
  cloud:
   gateway:
    routes:
     - id: GeneratePensionerDetails
       uri: lb://GeneratePensionerDetails
       predicates:
        - Path=/PensionerDetailByAadhaar/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9002/eureka
    fetch-registry: true
    register-with-eureka: true