server:
  port: 9002
spring:
  application:
    name: ProcesPension
  # Configure Database here
  datasource:
    url: jdbc:h2:mem:process_pension_db
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console.enable: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
    fetch-registry: true
    register-with-eureka: true
