server:
  port: 9003
spring:
  application:
    name: login

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true
    allowed:
      resources: /h2-console/**
    security:
      basic:
        enabled: true
        authorize-mode: NONE
  datasource:
    url: jdbc:h2:mem:pms
    username: sa
    password:
    driver-class-name: org.h2.Driver
    jpa:
      hibernate:
        ddl-auto: create
      database-platform: org.hibernate.dialect.H2Dialect
      show-sql: true
logging:
  level:
    org.springframework.web: DEBUG
    enableLoggingRequestDetails: false
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    fetch-registry: true
#    register-with-eureka: true